"""Add Firmante FirmaCampania and campaign fields lema url_externa meta_firmas

Revision ID: 0e023bd10912
Revises: 70f5a36b7a69
Create Date: 2026-01-20 09:18:37.278729
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0e023bd10912'
down_revision: Union[str, None] = '70f5a36b7a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firmantes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('documento', sa.String(length=255), nullable=True),
    sa.Column('tipo_documento', sa.String(length=20), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('pais_id', sa.Uuid(), nullable=True),
    sa.Column('codigo_postal', sa.String(length=20), nullable=True),
    sa.Column('acepta_comunicaciones', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['pais_id'], ['paises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firmantes_eliminado'), 'firmantes', ['eliminado'], unique=False)
    op.create_index(op.f('ix_firmantes_email'), 'firmantes', ['email'], unique=True)
    op.create_index(op.f('ix_firmantes_pais_id'), 'firmantes', ['pais_id'], unique=False)
    op.create_table('firmas_campania',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campania_id', sa.Uuid(), nullable=False),
    sa.Column('firmante_id', sa.Uuid(), nullable=False),
    sa.Column('fecha_firma', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('acepta_terminos', sa.Boolean(), nullable=False),
    sa.Column('verificado', sa.Boolean(), nullable=False),
    sa.Column('fecha_verificacion', sa.DateTime(), nullable=True),
    sa.Column('ip_origen', sa.String(length=50), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['campania_id'], ['campanias.id'], ),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['firmante_id'], ['firmantes.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firmas_campania_campania_id'), 'firmas_campania', ['campania_id'], unique=False)
    op.create_index(op.f('ix_firmas_campania_eliminado'), 'firmas_campania', ['eliminado'], unique=False)
    op.create_index(op.f('ix_firmas_campania_fecha_firma'), 'firmas_campania', ['fecha_firma'], unique=False)
    op.create_index(op.f('ix_firmas_campania_firmante_id'), 'firmas_campania', ['firmante_id'], unique=False)
    op.add_column('campanias', sa.Column('lema', sa.String(length=500), nullable=True))
    op.add_column('campanias', sa.Column('url_externa', sa.String(length=500), nullable=True))
    op.add_column('campanias', sa.Column('meta_firmas', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campanias', 'meta_firmas')
    op.drop_column('campanias', 'url_externa')
    op.drop_column('campanias', 'lema')
    op.drop_index(op.f('ix_firmas_campania_firmante_id'), table_name='firmas_campania')
    op.drop_index(op.f('ix_firmas_campania_fecha_firma'), table_name='firmas_campania')
    op.drop_index(op.f('ix_firmas_campania_eliminado'), table_name='firmas_campania')
    op.drop_index(op.f('ix_firmas_campania_campania_id'), table_name='firmas_campania')
    op.drop_table('firmas_campania')
    op.drop_index(op.f('ix_firmantes_pais_id'), table_name='firmantes')
    op.drop_index(op.f('ix_firmantes_email'), table_name='firmantes')
    op.drop_index(op.f('ix_firmantes_eliminado'), table_name='firmantes')
    op.drop_table('firmantes')
    # ### end Alembic commands ###
